#include <cstdlib>
#include <iostream>
#include <fstream> 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

using namespace std;
 
int main(int argc, char *argv[])
{  
    
    FILE * fp;
    fp = fopen(argv[1], "w");
    fprintf(fp, ">scaffold_1_8.fa\n");
    fprintf(fp, "TTAACTTGCTAGCATGATGCTAATTTCGTGGCATGGCGAAAATCCGTAGATCTGAAGAGACCTGCGGTTCTTTTTATATAGAGCGTAAATACACTCAATACCTTTTAAAGTATTCTTTGCTGTATTGATACTTTGATACCTTGTCTTTCTTACTTTAATATGACGGTGATCTTGCTCAATGAGGTTATTCAGATATTTCGATGTACAATGGCAGTCAGGTTTAAGTTTAAAAGCTTTAATTACTTTAACCATTGCTACCTTCGTTGAAGGTGCCTGATCTGTAATTACCTTTTGAGGTTTACCAAATTGTTTAATGAGACGTTTGATAAACGCATATGC\n");
    
}
